### PR TITLE
Launching single devices

### PR DESCRIPTION
**Pull request by pjakubczyk**
Instead of launching all devices from the configuration I think it's better to split the task into smaller steps. Each small task starts one device. At the end create a master tasks which combine them.

still WIP!

### CODE REVIEW

**Comment by pjakubczyk** [comment]
If you like the approach I would like to work on unit tests. 
Then do the same with Finish task

**Comment by eyal-lezmy** [comment]
Hi @pjakubczyk ,
First, thanks a lot for trying to contribute.
Your proposition seems interesting. I like the idea of having one single task by device to be launched/stopped. It will allow us to easily manage parallel launches using `ParallelizableTask` in the future.

I have a few remarks concerning your first implementation. I know this is a WIP but I want a discussion about how it could be done properly:
1. You do not support `productFlavors`:

You cannot run the same task several times, so today, for each flavor, we need to create a dedicated task for the devices launches and another for the devices stops. Following your idea we will need to create, for each flavor, one task per device launch. 
In this way, the `connectedAndroidTestFlavor1Debug` task cannot simply depends on `GenymotionSingleLaunchTask` because it will include more than the `flavor1` related tasks.

2.`GenymotionLaunchTask` needs to be refactored to remove the `TaskAction`
3. All the task creation/linking should be done on `injectTasks()` mehod
4. We need unit tests, but you already planned to write it.

So, my opinion is that I like your idea. It will imply a few deep changes on the tasks injections but it could be done cleanly. 

Let me know if you have questions about these feedback.

**Comment by tomaszrykala** [comment]
:+1:  for this feature.

**Comment by eyal-lezmy** [comment]
This PR is opened for too long. I close it feel free to open a new one for further contribution and thanks a lot for this input!

**Pull request closed without merging**
